[program:bafa]
command=/home/test/bafa/bafa
directory=/home/test/bafa
autostart=true
autorestart=true
startretries=3
user=test
stdout_logfile=/var/log/supervisor/bafa.log
stderr_logfile=/var/log/supervisor/bafa_error.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
